version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: '@types/jquery'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: '@types/simple-peer'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'handlebars'
      - dependency-name: 'pixi-particles'
      - dependency-name: 'pixi.js'
      - dependency-name: 'socket.io-client'
      - dependency-name: 'tinymce'
